import { Link } from 'react-router-dom';
import MedCheckLogo from '../components/MedCheckLogo';

function MedicalDisclaimer() {
  return (
    <div
      style={{
        fontFamily: "'DM Sans', sans-serif",
        background: '#f8fafc',
        minHeight: '100vh',
      }}
    >
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&family=Syne:wght@700;800&display=swap');

        .hero-bg {
          background: linear-gradient(135deg, #0c1f35 0%, #0a2a4a 40%, #0d3b6e 70%, #0ea5e9 100%);
          position: relative;
          overflow: hidden;
        }

        .hero-grid {
          position: absolute;
          inset: 0;
          background-image:
            linear-gradient(rgba(14,165,233,0.08) 1px, transparent 1px),
            linear-gradient(90deg, rgba(14,165,233,0.08) 1px, transparent 1px);
          background-size: 60px 60px;
        }

        .document-card {
          background: white;
          border-radius: 24px;
          border: 1px solid #e2e8f0;
          padding: 48px;
          box-shadow: 0 4px 20px rgba(15,23,42,0.03);
          line-height: 1.8;
          color: #334155;
        }

        .section-tag {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          background: #EFF9FF;
          color: #0284c7;
          font-size: 13px;
          font-weight: 600;
          padding: 6px 14px;
          border-radius: 50px;
          border: 1px solid #BAE6FD;
          margin-bottom: 16px;
          text-transform: uppercase;
        }

        .disclaimer-alert {
          background: #FFFBEB;
          border-left: 4px solid #F59E0B;
          border-radius: 12px;
          padding: 24px;
          margin-bottom: 32px;
          color: #78350F;
          font-weight: 500;
        }

        h2 {
          font-family: 'Syne', sans-serif;
          font-size: 24px;
          color: #0f172a;
          margin-top: 36px;
          margin-bottom: 16px;
          font-weight: 700;
        }

        p {
          margin-bottom: 20px;
          font-size: 15px;
        }
      `}</style>

      {/* HERO */}
      <section className="hero-bg" style={{ padding: '80px 24px', position: 'relative' }}>
        <div className="hero-grid"></div>
        <div style={{ position: 'relative', zIndex: 2, maxWidth: 900, margin: '0 auto', textAlign: 'center' }}>
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 20 }}>
            <MedCheckLogo size="md" />
          </div>
          <div className="section-tag">✦ Health Information Notice</div>
          <h1
            style={{
              fontFamily: 'Syne, sans-serif',
              fontWeight: 800,
              fontSize: 'clamp(32px, 6vw, 56px)',
              color: 'white',
              lineHeight: 1.1,
              marginBottom: 16,
              letterSpacing: '-1.5px',
            }}
          >
            Medical Disclaimer
          </h1>
          <p style={{ color: 'rgba(186,230,253,0.85)', fontSize: 16, maxWidth: 600, margin: '0 auto' }}>
            Understanding the scope and limitations of AI-powered health evaluations.
          </p>
        </div>
      </section>

      {/* CONTENT */}
      <section style={{ padding: '80px 24px' }}>
        <div style={{ maxWidth: 850, margin: '0 auto' }}>
          <div className="document-card">
            <div className="disclaimer-alert">
              ⚠️ <strong>CRITICAL WARNING:</strong> MedCheck does not provide medical diagnoses. If you have an emergency, sudden severe pain, chest tightness, difficulty breathing, or another life-threatening issue, seek professional emergency medical services immediately.
            </div>

            <h2>1. Informational Purposes Only</h2>
            <p>
              The content, outputs, condition correlations, severity indexes, and specialist suggestions generated by the MedCheck symptom checker are designed purely for informational and educational helper purposes. Under no circumstances should these inputs or results be treated as a medical consultation, diagnosis, prognosis, or prescription.
            </p>

            <h2>2. No Doctor-Patient Relationship</h2>
            <p>
              Your interactions with MedCheck, its artificial intelligence algorithms, or directories do not establish a doctor-patient relationship. No medical guidance is provided on the platform, and the system is not licensed to practice clinical medicine.
            </p>

            <h2>3. Consult a Licensed Healthcare Professional</h2>
            <p>
              AI symptom checks should not be used as a substitute for contacting, scheduling, or seeking advice from a licensed medical professional or physician. Never delay seeking care, ignore clinical guidelines, or adjust prescribed therapies because of insights displayed by MedCheck.
            </p>

            <h2>4. Disclaimer of Warranties</h2>
            <p>
              Although we strive to base our AI evaluations on established medical datasets, MedCheck does not guarantee the accuracy, completeness, or reliability of the analysis. You use the service entirely at your own risk.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}

export default MedicalDisclaimer;
