import { Link } from 'react-router-dom';
import MedCheckLogo from '../components/MedCheckLogo';

function TermsOfService() {
  return (
    <div
      style={{
        fontFamily: "'DM Sans', sans-serif",
        background: '#f8fafc',
        minHeight: '100vh',
      }}
    >
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600;700&family=Syne:wght@700;800&display=swap');

        .hero-bg {
          background: linear-gradient(135deg, #0c1f35 0%, #0a2a4a 40%, #0d3b6e 70%, #0ea5e9 100%);
          position: relative;
          overflow: hidden;
        }

        .hero-grid {
          position: absolute;
          inset: 0;
          background-image:
            linear-gradient(rgba(14,165,233,0.08) 1px, transparent 1px),
            linear-gradient(90deg, rgba(14,165,233,0.08) 1px, transparent 1px);
          background-size: 60px 60px;
        }

        .document-card {
          background: white;
          border-radius: 24px;
          border: 1px solid #e2e8f0;
          padding: 48px;
          box-shadow: 0 4px 20px rgba(15,23,42,0.03);
          line-height: 1.8;
          color: #334155;
        }

        .section-tag {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          background: #EFF9FF;
          color: #0284c7;
          font-size: 13px;
          font-weight: 600;
          padding: 6px 14px;
          border-radius: 50px;
          border: 1px solid #BAE6FD;
          margin-bottom: 16px;
          text-transform: uppercase;
        }

        h2 {
          font-family: 'Syne', sans-serif;
          font-size: 24px;
          color: #0f172a;
          margin-top: 36px;
          margin-bottom: 16px;
          font-weight: 700;
        }

        p {
          margin-bottom: 20px;
          font-size: 15px;
        }

        ul {
          margin-bottom: 24px;
          padding-left: 20px;
        }

        li {
          margin-bottom: 10px;
          font-size: 15px;
        }
      `}</style>

      {/* HERO */}
      <section className="hero-bg" style={{ padding: '80px 24px', position: 'relative' }}>
        <div className="hero-grid"></div>
        <div style={{ position: 'relative', zIndex: 2, maxWidth: 900, margin: '0 auto', textAlign: 'center' }}>
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 20 }}>
            <MedCheckLogo size="md" />
          </div>
          <div className="section-tag">✦ Terms & Rules</div>
          <h1
            style={{
              fontFamily: 'Syne, sans-serif',
              fontWeight: 800,
              fontSize: 'clamp(32px, 6vw, 56px)',
              color: 'white',
              lineHeight: 1.1,
              marginBottom: 16,
              letterSpacing: '-1.5px',
            }}
          >
            Terms of Service
          </h1>
          <p style={{ color: 'rgba(186,230,253,0.85)', fontSize: 16, maxWidth: 600, margin: '0 auto' }}>
            Last updated: May 29, 2026. Please read our guidelines before using MedCheck.
          </p>
        </div>
      </section>

      {/* CONTENT */}
      <section style={{ padding: '80px 24px' }}>
        <div style={{ maxWidth: 850, margin: '0 auto' }}>
          <div className="document-card">
            <p>
              Welcome to MedCheck. By accessing or using our website, AI symptom assessment features, or database directories, you agree to comply with and be bound by the following Terms of Service.
            </p>

            <h2>1. Acceptable Use & Registration</h2>
            <p>
              To use MedCheck, you agree to:
            </p>
            <ul>
              <li>Provide accurate, truthful details about your symptoms and medical contexts.</li>
              <li>Maintain the confidentiality of your credentials and account password.</li>
              <li>Use our services only for personal, non-commercial informational purposes.</li>
            </ul>

            <h2>2. No Medical Advice Provided</h2>
            <p>
              You explicitly acknowledge that:
            </p>
            <ul>
              <li><strong>Informational Content:</strong> All summaries, urgency levels, and health condition correlations are generated by an AI model and do not constitute professional diagnosis or clinical advice.</li>
              <li><strong>Not an Emergency Service:</strong> If you are experiencing a severe or life-threatening medical event, call emergency services immediately. Do not rely on MedCheck for critical situations.</li>
            </ul>

            <h2>3. Account Suspension & Termination</h2>
            <p>
              We reserve the right to limit access or terminate accounts that breach these terms, engage in automated querying, or attempt to compromise site infrastructure security.
            </p>

            <h2>4. Limitation of Liability</h2>
            <p>
              MedCheck, its developers, and contributors are not liable for any actions, healthcare choices, or diagnosis outcomes made as a result of using the AI symptom checker or platform summaries. Always consult a qualified physician.
            </p>

            <h2>5. Revisions of Terms</h2>
            <p>
              We reserve the right to update these terms at any time. Changes will be posted to this page with an updated modification date.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}

export default TermsOfService;
